cli/Cargo.toml
cli/src/display.rs
cli/src/main.rs
cli/src/session.rs

feat: box style display results

---

cli/Cargo.toml
driver/Cargo.toml
driver/src/schema.rs

fix(driver): is_numeric check inner type for Nullable

---

driver/Cargo.toml
driver/src/schema.rs
driver/tests/driver/select_simple.rs
tests/Makefile

wait for: https://github.com/datafuselabs/databend/pull/11251 release

fix(driver): better handle null datatype

---

cli/src/session.rs

fix(cli): delete show affected rows

---

cli/src/display.rs

1. fix head name is not ascii may cause panic
2. only total length_length > max_width , the result need to be pruned.
3. process bottom rows element_size.

fix(cli): fix head name is not ascii string error

---

Cargo.toml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json
cli/src/display.rs
cli/src/session.rs

feat(cli): better new line mode

---

Cargo.toml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json
core/src/client.rs

feat(core): retry for 503

---

core/Cargo.toml
core/build.rs
core/src/client.rs
licenserc.toml

feat(core): set custom request UA for client

---

cli/src/config.rs

fix(conf): add display info into config

---

.github/workflows/bindings.python.yml
sql/src/schema.rs

- fix: https://github.com/datafuselabs/bendsql/issues/222

fix(driver): support data type Nothing

---

cli/src/main.rs
cli/src/session.rs

fix: https://github.com/datafuselabs/databend/issues/11904

fix(cli): expose error for handle_reader

---

cli/src/main.rs

- fix: https://github.com/datafuselabs/bendsql/issues/233

fix(cli): require_equals for query arg

---

README.md
cli/src/config.rs

fix: default config file to ~/.bendsql/config.toml

---

bindings/nodejs/generated.js
bindings/nodejs/index.d.ts
bindings/nodejs/src/lib.rs
cli/src/config.rs
cli/src/display.rs
cli/src/main.rs
cli/src/session.rs
driver/src/conn.rs
driver/src/flight_sql.rs
driver/src/lib.rs
driver/src/rest_api.rs
sql/src/rows.rs

* rename `QueryProgress` to `ServerStats`
* rename `RowProgressIterator` to `RowStatsIterator`
* rename `RowOrProgress` to `RowOrStats`

feat(cli): support arg --time=server/local

---

core/Cargo.toml
core/src/client.rs
driver/src/rest_api.rs

feat: generate query id on request

---

cli/src/session.rs

For better error display.
cc @wubx

fix(cli): send formatted query to server

---

cli/src/session.rs

link to : https://github.com/datafuselabs/databend/issues/13490

feat: check read line err

---

bindings/python/src/blocking.rs

fix(pythonbinding): raise python exception in iter_query

---

core/src/presign.rs

fix  https://github.com/datafuselabs/databend/issues/14192

fix(core): oss presign fail caused by invalid Content-Length

---

cli/src/main.rs
cli/src/trace.rs
core/src/client.rs
core/src/response.rs

feat: display server warnings on repl

---

sql/Cargo.toml
sql/src/error.rs
sql/src/schema.rs
sql/src/value.rs

related: https://github.com/datafuselabs/databend/pull/14235

feat: add binary type

---

bindings/nodejs/src/lib.rs
bindings/python/src/types.rs

fix https://github.com/datafuselabs/bendsql/pull/330#issuecomment-1882223548

fix: add Binary type for python/nodejs binding

---

cli/src/main.rs
cli/src/session.rs

feat(cli): add --check for server status check

---

cli/Cargo.toml
cli/src/main.rs
cli/src/trace.rs
core/src/client.rs
tests/docker-compose.yaml

feat(cli): show server warnings with color

---

cli/src/session.rs
cli/tests/01-put.result
cli/tests/01-put.sh

fix(cli): change token copy to QueryKind::Query

---

README.md
cli/src/main.rs
cli/src/session.rs
cli/test.sh
core/src/client.rs
core/src/presign.rs
core/tests/core/stage.rs
driver/src/rest_api.rs
driver/tests/driver/load.rs

feat: support argument presign=auto/detect/on/off

---

core/src/request.rs

part of https://github.com/datafuselabs/databend/issues/14789

feat: support transaction.

---

core/src/client.rs

fix: should call handle_session() when query fail.

---

README.md
cli/Cargo.toml
cli/src/session.rs

Now we support these commands, related #354
| `!exit` | Exit bendsql |
| `!quit` | Exit bendsql |
| `!configs` | Show current settings |
| `!set` | Set settings |
| `!source file` | Source file and execute |

feat: add more commands

---

bindings/nodejs/src/lib.rs
bindings/nodejs/tests/binding.js

Convert `Array`, `Map`, `Tuple`, `Date`, `Timestamp` to `Node.js` native types.

feat(bindings/nodejs): support nested types Array,Map,Tuple 

---

.github/actions/setup/action.yml
.github/workflows/bindings.nodejs.yml
.github/workflows/bindings.python.yml
bindings/python/pyproject.toml
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py

feat(bindings/python): support nested types Array,Map,Tuple

---

Cargo.toml
bindings/python/Cargo.toml
bindings/python/src/asyncio.rs
bindings/python/src/lib.rs
bindings/python/src/types.rs
deny.toml

* patch `pyo3-asyncio` temporarily

chore(bindings/python): upgrade pyo3 to 0.21

---

cli/src/session.rs

fix(cli): support exit & quit for exit

---

core/src/request.rs

otherwise, changes to these fields lead to incompatibility.

refactor(core): SessionState hide fields of no interest.

---

sql/src/schema.rs

fix: support parsing both Nullable(T) and T NULL

---

.github/workflows/bindings.python.yml

chore(bindings/python): enable aarch64 target

---

Cargo.toml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-arm64-gnu/package.json
bindings/nodejs/npm/linux-arm64-musl/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/linux-x64-musl/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json

chore: bump version to 0.17.3

---

.github/workflows/bindings.nodejs.yml

fix(ci): add target aarch64-unknown-linux-gnu for nodejs binding

---

cli/src/config.rs

close:  https://github.com/datafuselabs/bendsql/issues/434

fix(cli): change max_display_rows 40 to 1000

---

cli/Cargo.toml
cli/src/args.rs

fix(cli): percent encode password for dsn

---

core/src/client.rs

related: https://github.com/datafuselabs/databend-go/pull/134/files

feat(driver): Add route hint, make load balancer easier to route queries

---

cli/src/session.rs

- for: https://github.com/datafuselabs/bendsql/issues/468

fix(cli): set limit for prompt keyword sql

---

bindings/nodejs/src/lib.rs
bindings/python/src/blocking.rs
bindings/python/src/types.rs
cli/Cargo.toml
cli/src/main.rs
cli/src/session.rs
core/src/client.rs
sql/Cargo.toml

- exit client if login failed with password wrong
- fix some clippy error
- bump jsonb 0.4.1

fix: exit client if login failed with password wrong

---

.github/workflows/release.yml
cli/build.rs
cli/src/config.rs
cli/src/display.rs
cli/src/main.rs
cli/src/session.rs
cli/src/web.rs
frontend/src/hooks/useProfileData.ts

This pr:
- Introduce server config section
- Introduce dedicated server impl
part of #490 
cc @Maricaya

feat: introduce dedicated server

---

.github/workflows/ttc.yml
core/src/client.rs

chore: update ttc yml

---

Cargo.toml
bindings/python/src/blocking.rs
bindings/python/tests/cursor/steps/binding.py
driver/Cargo.toml
sql/Cargo.toml

fix(py): fix incorrect description in cursor

---

cli/src/display.rs
licenserc.toml
sql/src/schema.rs

If there are lots columns in table, the render style looks like:

chore: use comfy_table::ContentArrangement::Dynamic

---

.cargo/audit.toml
.github/workflows/bindings.python.yml
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py
bindings/python/tests/cursor/steps/binding.py
core/Cargo.toml
core/src/client.rs
deny.toml
tests/nox/noxfile.py

and add compat test for py behave test

feat: streaming load support session.
