cli/Cargo.toml
cli/README.md
cli/src/display.rs
cli/src/session.rs

feat: client support flight progress

---

cli/Cargo.toml
cli/src/config.rs
cli/src/main.rs
cli/src/session.rs

changes:
1. better auto output format
TSV for non-repl mode;  Table for repl mode.
2. repspect last sql query:  
```
❯ echo "select 3,5" | ./target/release/bendsql -u sundy -p abc --port 8900 -h127.0.0.1 --flight -o csv
3,5
```

chore: better format

---

cli/src/config.rs
cli/src/display.rs
cli/src/main.rs
cli/src/session.rs

simple way to measure performance:
```
❯ bendsql --time  --query "select sum(number) from numbers(10000000000)"
0.271
```

feat: add output null and time

---

cli/Cargo.toml
cli/build.rs
cli/src/main.rs
cli/src/session.rs

```
❯ ./target/debug/bendsql -V
bendsql 0.3.4-9f09312(2023-04-28T02:49:12.351594000Z)
```
```
❯ ./target/debug/bendsql   
Welcome to BendSQL 0.3.4-9f09312(2023-04-28T02:49:12.351594000Z).
Trying connect to localhost:8000 as user root.
```

chore(cli): better version with build info

---

cli/src/config.rs
cli/src/session.rs

```
:) .multi_line false
:) select 3
SELECT
3
┌───────┐
│   3   │
│ UInt8 │
├───────┤
│     3 │
└───────┘
1 row in 0.005 sec. Processed 1 rows, 1B (192.19 rows/s, 192B/s)
:) select 4
SELECT
4
┌───────┐
│   4   │
│ UInt8 │
├───────┤
│     4 │
└───────┘
1 row in 0.005 sec. Processed 1 rows, 1B (187.04 rows/s, 187B/s)
```

feat: add multi line config

---

README.md
cli/src/config.rs
cli/src/display.rs

default `max_display_rows` is 40
```
:) .max_display_rows 10
:) select 1, 'a', number, 2 from numbers(1000);
SELECT
1,
'a',
number,
2
FROM
numbers(1000)
┌──────────────────────────────────────┐
│      1     │   'a'  │ number │   2   │
│    UInt8   │ String │ UInt64 │ UInt8 │
├────────────┼────────┼────────┼───────┤
│          1 │ a      │      0 │     2 │
│          1 │ a      │      1 │     2 │
│          1 │ a      │      2 │     2 │
│          1 │ a      │      3 │     2 │
│          1 │ a      │      4 │     2 │
│          · │ ·      │      · │     · │
│          · │ ·      │      · │     · │
│          · │ ·      │      · │     · │
│          1 │ a      │    995 │     2 │
│          1 │ a      │    996 │     2 │
│          1 │ a      │    997 │     2 │
│          1 │ a      │    998 …
```

feat: support config max_display_rows

---

cli/src/session.rs

Fix paste SQL into cli with newline.
```
select
1
from numbers(3);
```

fix(cli): fix paste sql with newline

---

core/src/client.rs
core/src/error.rs
driver/src/error.rs
driver/src/flight_sql.rs

feat: support dsn arg tls_ca_file

---

Cargo.toml
bindings/nodejs/npm/darwin-arm64/package.json
bindings/nodejs/npm/darwin-x64/package.json
bindings/nodejs/npm/linux-x64-gnu/package.json
bindings/nodejs/npm/win32-x64-msvc/package.json
bindings/nodejs/package.json
cli/README.md
cli/src/ast/mod.rs
cli/src/ast/tokenizer.rs
cli/src/session.rs
cli/tests/http/04-put.result
cli/tests/http/04-put.sh
core/src/client.rs
driver/Cargo.toml
driver/src/conn.rs
driver/src/rest_api.rs
sql/Cargo.toml
sql/src/error.rs
sql/src/rows.rs
sql/src/schema.rs

refer to snowflake's get/put stmt: https://docs.snowflake.com/en/sql-reference/sql/get
syntax: `PUT file://<path_to_file>/<filename> internalStage` and `GET internalStage file://<path_to_file>`
```
🐳 @default:) put fs:///Users/sundy/*.sh   @s4/abc;
put fs:///Users/sundy/*.sh   @s4/abc
┌────────────────────────────────────────────┐
│               file               │  status │
│              String              │  String │
├──────────────────────────────────┼─────────┤
│ /Users/sundy/databend_all_ssb.sh │ SUCCESS │
│ /Users/sundy/fetch.sh            │ SUCCESS │
│ /Users/sundy/rustup-init.sh      │ SUCCESS │
│ /Users/sundy/source_fs.sh        │ SUCCESS │
│ /Users/sundy/source_minio.sh     │ SUCCESS │
│ /Users/sundy/source_s3.sh        │ SUCCESS │
│ /Users/sundy/start.sh            │ …
```

feat: support get/put stmt

---

cli/Cargo.toml

Update backtrace support to nightly's new Error::provide API (rust-lang/rust#113464, #319)
https://github.com/dtolnay/anyhow/releases/tag/1.0.73

chore: update anyhow to 1.0.75.

---

driver/Cargo.toml
sql/Cargo.toml

Consistency with the version of arrow-rs that Databend relies on

chore: update arrow to 45.0.0

---

cli/src/config.rs
cli/src/display.rs

* Closes: https://github.com/datafuselabs/bendsql/issues/74
```
everpcpc@(system)/tpch_10> .expand auto
everpcpc@(system)/tpch_10> select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part, supplier, partsupp, nation, region where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_size = 15 and p_type like '%BRASS' and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost = ( select min(ps_supplycost) from partsupp, supplier, nation, region where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' ) order by s_acctbal desc, n_name, s_name, p_partkey limit 1;
-[ RECORD 1 ]-----------------------------------
s_acctbal: 9994.37 …
```

feat(cli): support expaneded display for table format

---

.github/workflows/bindings.nodejs.yml
.github/workflows/bindings.python.yml
.github/workflows/publish.yml
bindings/python/Cargo.toml

Maturin use it to add a Source Code project url if provided.
Avoid error `Invalid value for project_urls. Error: Use both a label and an URL.` in pypi publish.

fix(bindings/python): remove repository field for maturin

---

cli/src/session.rs
core/src/stage.rs

- fix: https://github.com/datafuselabs/bendsql/issues/268

fix(core): allow stage with empty path

---

cli/src/main.rs
core/src/client.rs
driver/src/flight_sql.rs

- fix: https://github.com/datafuselabs/bendsql/issues/281

fix: return error for bad argument sslmode

---

core/src/client.rs
core/src/request.rs
core/src/response.rs

SessionConfig is used to store the session state across multiple queries in one client session.
After user setting `SET ROLE role1`, session config will contain `role: role1` in the response, then the client can pass `role: role1` to the next query's header, thus allows user to change role in a client view.
The `secondary_roles` is still under development in databend (https://github.com/datafuselabs/databend/pull/13673) but IMHO adding a `secondary_roles` field will not break the deserialization even the server did not respond this field at all.

feat(core): handle role and secondary_roles in SessionConfig

---

core/src/client.rs
core/src/request.rs
core/src/response.rs

this PR handles the SessionState as a whole:
1. on starting each query, it send the SessionState to the query instance
2. query instance responses a new SessionState to the client, and the client just save it
3. client pick the reponded SessionState to the next query
this may help reduce the cognize load when adding things into the SessionState, do not need `handle_session()` and `make_session()` with understanding of the fields, all we need is to pass it as a whole.

fix: handle SET ROLE properly

---

cli/src/args.rs
cli/src/config.rs
cli/src/main.rs
cli/tests/00-base.sql
cli/tests/01-put.sh
cli/tests/data/ontime.sql
cli/tests/http/01-load_stdin.sh
cli/tests/http/02-load_file.sh
cli/tests/http/03-load_file_gzip.sh
cli/tests/http/04-args-database.result
cli/tests/http/04-args-database.sh
driver/tests/driver/select_iter.rs

feat(cli): support setting database -D with DSN

---

driver/src/flight_sql.rs
driver/src/rest_api.rs

Now execute sql:
```
echo "SELECT number, NTH_VALUE(number, 2) OVER (ORDER BY score DESC) FROM (select number::string number , number % 100 as score from numbers(300000000) ) ignore_result;" | bendsql
```
The CPU load just takes 0.1% instead of 100%.

fix(driver): don't call wake_by_ref in Poll::Pending

---

bindings/nodejs/src/lib.rs
bindings/python/src/types.rs
cli/src/ast/tokenizer.rs
cli/src/display.rs
sql/Cargo.toml
sql/src/error.rs
sql/src/schema.rs
sql/src/value.rs

Add new token `GEOMETRY` and new data type `Geometry`.

feat: add geometry data type

---

core/src/response.rs
driver/src/rest_api.rs

1. client used to wait for schema in the server side.  So the user experience has not worsened.
2. when API `query_iter` is used. user is expected to used the result, so need to wait however.
3. other ways to handle the late schema need refactor of both user and inner interfaces,   let`consider it later.

fix: the first resp may not contain schema.

---

bindings/nodejs/tests/binding.js
bindings/python/.gitignore
bindings/python/src/types.rs
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py
bindings/tests/features/binding.feature

feat(bindings/python): convert decimal values to python Decimal

---

cli/src/session.rs
cli/tests/00-base.result
cli/tests/00-base.sql
driver/tests/driver/select_simple.rs
sql/Cargo.toml
sql/src/cursor_ext/cursor_checkpoint_ext.rs
sql/src/cursor_ext/cursor_read_bytes_ext.rs
sql/src/cursor_ext/cursor_read_number_ext.rs
sql/src/cursor_ext/cursor_read_string_ext.rs
sql/src/cursor_ext/mod.rs
sql/src/schema.rs
sql/src/value.rs

- support decode nested types from string to values
- boolean value display `true` and `false` instead of `1` and `0`
- flight sql convert binary type to binary value instead of string value
- fix data type parser to support nested nullable type, like `Nullable(Map(String, String NULL))`

feat: support decode nested types from string to values

---

bindings/nodejs/README.md
bindings/python/README.md
driver/README.md

Add type mapping for `Rust` driver and `Python`, `Node.js` binding.

chore(docs): add type mappings

---

cli/src/display.rs
cli/src/main.rs
cli/test.sh
driver/src/rest_api.rs
sql/src/cursor_ext/cursor_read_bytes_ext.rs

1. Config is immutable, we will not update the config by args.
2. The connection arg is mutable which will be updated by args.
Add tests case to cover none-root auth

fix: fix args parser

---

cli/src/config.rs
cli/src/main.rs
cli/src/session.rs

With config field `no_auto_complete`.
To disable loading tables and fields for auto completion, offers a quicker start.
- fixes: #429

feat(cli): new argument no-auto-complete

---

cli/src/session.rs
driver/src/conn.rs

In PR https://github.com/datafuselabs/databend/pull/16031
We support the feature that user can continue login and change the password after the password expires. In this case, the user cannot perform other operations except changing the password. As a result, the SQL `select version()`, which is automatically sent by `BendSQL` fails to be executed and exits, causing the user can't change the password. This PR allows `select version()` to fail and not exit, and user can continue change password.

fix: allow select version() failed

---

cli/src/display.rs
cli/src/session.rs

Exit client after changing the current user's password, user can login again with the new password.
This is because `BendSQL` continue use old password for following queries, which will result in login failure with message `Query Page failed with status 401 Unauthorized: {"error":{"code":"401","message":"wrong password"}}`

chore: exit client after changing current user's password

---

.github/workflows/release.yml
cli/build.rs
cli/src/display.rs
cli/src/web.rs

chore: use build.rs to build frontend resources

---

cli/src/session.rs

Test:
in main branch:
If databend-query not start, bendsql not exit.
```shell
➜  bendsql git:(main) cargo build --bin bendsql && ./target/debug/bendsql --query='select 1'
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
Error: APIError: RequestError: error sending request for url (http://localhost:8000/v1/query)
➜  bendsql git:(main) cargo build --bin bendsql && ./target/debug/bendsql                   
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
Welcome to BendSQL 0.22.2-b6f550d(2024-10-30T03:05:49.669884189Z).
Connecting to localhost:8000 as user root.
Connected to 
Started web server at 127.0.0.1:8080
:) select 1;
error: APIError: RequestError: error sending request for url (http://localhost:8000/v1/query)
```

chore: if return databend-query err should exit client

---

bindings/nodejs/tests/binding.js
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py
cli/src/main.rs
cli/src/session.rs
core/Cargo.toml
core/src/auth.rs
core/src/client.rs
core/src/error.rs
core/src/error_code.rs
core/src/global_cookie_store.rs
core/src/lib.rs
core/src/login.rs
core/src/response.rs
core/src/session.rs
core/src/stage.rs
deny.toml
driver/src/rest_api.rs
driver/tests/driver/main.rs
driver/tests/driver/session.rs
driver/tests/driver/temp_table.rs
sql/src/cursor_ext/cursor_read_bytes_ext.rs
sql/src/schema.rs
sql/src/value.rs
tests/Makefile
tests/docker-compose.yaml

feat:
1.  try to access `/v1/session/login`  to get session token and refresh token when init APIClient. it got 404,  do not use session token in the following request
3. uses session token when sending and polling query. it session token expired, renew token and retry
4.  upload_stage accept a  Reader, so it can not retry,  check for expired and renew before request.
5. call `/v1/session/logout` when drop  APIClient 
6. support cookie to carry session id with each request, and even if session_token is not used.
4. DSN add param `session_token=enable|disable`, disable by default now,  may changed to enable by default after stable
5. DSN add param `login=enable|disable`, enabled by default, so user can choose to disable if only one query in session
6. after this pr, temp table is …

feat: support server side session

---

core/src/error_code.rs

the message string itself contains a `\n` at the end， so the '.'  occupies a line by itself.

fix: fmt of error.

---

cli/src/args.rs
cli/src/main.rs
cli/src/session.rs
core/src/client.rs
core/src/lib.rs
driver/src/conn.rs
driver/src/flight_sql.rs
driver/src/rest_api.rs
sql/src/error.rs
sql/src/rows.rs
sql/src/schema.rs

refactor: pub only necessary items in databend-client.

---

cli/src/main.rs
cli/src/session.rs
core/src/client.rs
driver/src/conn.rs
driver/src/rest_api.rs

I`ll add `with` and `async with` support later after getting familiar with PyO3.

feat: Client add close function.

---

core/src/client.rs

3eb745e72c5b53bee28c2f6de4a7f208e0dfa795 made many client fields private. It exposed methods to get the port and host, but not the scheme. We are depending on the ability to fetch the scheme in `vectordotdev/vector` and so are currently [blocked from upgrading](https://github.com/vectordotdev/vector/pull/22027).
cc/ @everpcpc

refactor: re-expose scheme from client

---

sql/src/value.rs

Summary:
The MonthsDaysMicros struct’s new method incorrectly handled negative days and microseconds values, leading to incorrect bitwise representation and extraction. This PR addresses these issues by:
Casting days to u32 before casting to i128 to prevent sign extension. Casting microseconds to u64 before casting to i128 to prevent sign extension.

fix: Fix: Correct sign extension handling in months_days_micros struct

---

.github/workflows/bindings.python.yml
.gitignore
core/src/response.rs
driver/src/rest_api.rs

will be used for java binding to reduce number of JNI call.
part of https://github.com/databendlabs/bendsql/pull/553

feat: rest_api support fn query_row_batch

---

bindings/python/README.md
bindings/python/src/types.rs
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py
bindings/python/tests/cursor/steps/binding.py

Fix : https://github.com/databendlabs/bendsql/issues/552

feat: binding interval convert to python timedelta

---

cli/Cargo.toml
cli/src/config.rs
cli/src/display.rs
cli/src/gendata.rs
cli/src/session.rs

1.  enable duckdb crate only by 
```
#[cfg(any(
all(target_arch = "x86_64", target_os = "linux"),
all(target_arch = "aarch64", target_os = "macos")
))]
```
3.  support '\G' suffix in bendsql repl mode like MySQL

chore: enable duckdb crate  by arch

---

Cargo.toml
bindings/nodejs/tests/binding.js
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py
cli/src/display.rs
cli/src/session.rs
sql/src/raw_rows.rs
sql/src/rows.rs
sql/src/value.rs

1. display table discards some rows that are not needed because `bendsql` has a maximum number of rows to display. This can avoid panic caused by excessive data occupying too much memory.
2. using `String` instead of `&str` to convert to `Value` to avoid unneeded String copying.
3. upgrade `arrow` version to `54.0` for compatibe with `Databend`.

chore: table display discard some unused rows

---

cli/src/session.rs

ignore empty `;` line don't report an error.

chore: ignore empty SemiColon line

---

bindings/nodejs/src/lib.rs
bindings/python/Cargo.toml
bindings/python/src/asyncio.rs
bindings/python/src/blocking.rs
bindings/python/tests/asyncio/steps/binding.py
bindings/python/tests/blocking/steps/binding.py
bindings/python/tests/cursor/steps/binding.py
driver/src/rest_api.rs
sql/src/value.rs

- use LoadMethod::Stage by default,  Streaming Load need add session info
- executemany  reuse API stream_load instead of formating csv itself
- load_file tolerant old SQL without placeholder for fewer breaking change.
- fix interval parsing of python bindings

refactor: polish file load APIs.

---

README.md
cli/src/config.rs
cli/src/display.rs

Limit display render box max width, 0 means default to the size of the terminal. 65535 means no limit for max_width. 0-65535 means the min with value of config and terminal size.

feat: modify max_width

---

bindings/nodejs/src/lib.rs
bindings/nodejs/tests/binding.js

otherwise, console.log(schema.fields()) shows an empty array, which is misleading,  although we can get fields in it.
Schema not  changed to avoid breaking function `.fields()`.

feat: change Field from class to object. 
